language: objective-c
osx_image: xcode9.0.1
xcode_workspace: MarsRover.xcworkspace
xcode_scheme: MarsRoverTests
xcode_sdk: iphonesimulator11
before_install:
- gem install xcpretty
script:
- xcodebuild -scheme MarsRover -workspace MarsRover.xcworkspace -configuration 'Debug' -destination "platform=iOS Simulator,name=iPhone 8,OS=11." clean build test
